# Global
random_seed: 42
cache_path: ./resources/data/cache/
# Experiment
experiments_dir: ./experiments/
# Languages
src_lang_dir: ./resources/data/preprocessed/te/
tgt_lang_dir: ./resources/data/preprocessed/en/
